### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by funky-monkey** [jlopez/ane-testflight#1]
Hi Jesus, 

I followed your instructions, and have all the external git repos setup in the correct folders. When i run 'make ane' i get an fatal error for uikit/uikit.h

myhost:dist me$ make ane
make: xml: Command not found
  MACRO     extension.xml
  COMPC     com.testflightapp.sdk.TestFlight
Loading configuration file /SDK/flex_sdk_4.6_AIR_3.2_Stage3D/frameworks/airmobile-config.xml
/Users/funkymonkey/GitRepos/ane-testflight/dist/library.swc (2126 bytes)
  EXTRACT   library.swf
  OBJCXX    TestFlightLib.mm
In file included from ../src/ios/TestFlightLib.mm:8:
../src/ios/ane/src/NativeLibrary.h:8:9: fatal error: 'UIKit/UIKit.h' file not found
# import <UIKit/UIKit.h>

```
    ^
```

1 error generated.
make: **\* [TestFlightLib.o] Error 1

Am i missing a file? Or do i have something not setup correctly? Can you help me out with this? 

Best, 
Sidney

**Comment by jlopez** [comment]
Forgot to mention the make scripts require xmlstarlet. I'll add that to the documentation.
